name: butler-calendar
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - requests
  - beautifulsoup4
  - pytz
  - pip
  # dev
  - pre-commit
  - pytest
  - pytest-mock
  - responses
  - pip:
      - google-api-python-client
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
