name: "Weekly Run"

on:
    workflow_dispatch:
    schedule:
        # Run every Sunday at midnight
        - cron: "0 0 * * 0"

jobs:
  weekly-run:
    name: "Weekly Run"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version:
          - "3.12"
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ matrix.python-version }}
      cancel-in-progress: true
    steps:
      - name: "Checkout Infrastructure"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          activate-environment: butler_cal-dev

      - name: Install butler_cal
        run: |
          python --version
          pip install -e .[dev]

      - name: Run butler_cal
        run: |
          python -m butler_cal
        env:
            CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
            SA_CREDENTIALS: ${{ secrets.SA_CREDENTIALS }}
